const alphaUrls = [
  'https://www.brandeis.edu/facultyguide/letter.html?letter=A',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=B',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=C',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=D',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=E',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=F',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=G',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=H',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=I',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=J',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=K',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=L',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=M',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=N',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=O',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=P',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=Q',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=R',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=S',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=U',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=V',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=W',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=X',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=Y',
  'https://www.brandeis.edu/facultyguide/letter.html?letter=Z',

];

module.exports = alphaUrls;
